// English copy. Yeoman narrates in its speech bubble (sub.*, voiced); cat.* are its extra lines for interactions.
// Persona: a tsundere cat with a sunny boy's voice: a sulky face, proud and a little grumpy ("hmph"), warm
// underneath. Every number also appears in the piece's facts ledger.

export default {
  meta: {
    title: 'IceCube',
    tagline: 'A cubic kilometre of darkness, waiting for one faint flash from the universe',
    question: 'How can an invisible particle tell us where in the sky to look?',
    start: 'Start the tour',
    explore: 'Explore freely',
    duration: 'Interactive film · about {min} minutes · pause, scrub or take over at any time', // {min}: filled in by the HUD
    nobel: 'The 2026 Nobel Prize in Physics goes to Francis Halzen, for the IceCube Neutrino Observatory and the discovery of high-energy neutrinos from space.',
    nobelLink: 'Official Nobel press release',
    by: 'CosmicTraveler – Yeoman',
    teaching: 'Teaching simulation: the array follows official spacings; per-DOM signals are simulated.',
  },
  ui: {
    play: 'Play',
    pause: 'Pause',
    resume: 'Back to the tour',
    lang: '中文',
    voiceOn: 'Voice: on',
    voiceOff: 'Voice: off',
    voiceNone: 'Voice: n/a',
    volume: 'Volume',
    volVoice: 'Voice',
    volMusic: 'Music',
    qualityLabel: 'Quality',
    qAuto: 'Auto',
    qHigh: 'High',
    qMedium: 'Medium',
    qLow: 'Battery',
    soundOn: 'Sonification: on',
    soundOff: 'Sonification: off',
    sources: 'Sources',
    lab: 'Lab',
    settings: 'Display',
    realSize: 'True size',
    enlarged: 'Enlarged markers',
    sizeNote: 'Enlarged markers: same positions, drawn bigger',
    realNote: 'True size: a DOM is 33 cm across and vanishes at this scale; the lines are guides',
    reduceMotion: 'Reduce motion',
    quality: 'Quality',
    qualityHigh: 'High',
    qualityLow: 'Battery',
    layers: 'Layers',
    layerPhysics: 'Physics',
    layerRecord: 'Detector record',
    layerReco: 'Reconstruction',
    physTime: 'Physical time',
    slowmo: 'Slow motion',
    stepBack: 'Back 100 ns',
    stepFwd: 'Forward 100 ns',
    legendTime: 'Time recorded',
    early: 'early',
    late: 'late',
    legendSize: 'Marker size = amount of light',
    legendRecord: 'A coloured marker means "signal recorded"; the DOM does not glow',
    legendResid: 'Time residual: recorded − predicted',
    residEarly: 'earlier',
    residOk: 'on time',
    residLate: 'later',
    close: 'Close',
    replay: 'Replay',
    chapter: 'Chapter',
    depth: 'Depth',
    meters: 'm',
    keyboard: 'Space play/pause · ←/→ nudge · 1–6 chapters · L layers · R size',
  },
  chapters: ['Surface', 'Scale', 'Slow motion', 'Reconstruction', 'Origin', 'Back to the sky'],
  // Narration: Yeoman says these lines in its speech bubble (no subtitles); `tts` holds the spoken form where
  // symbols or numbers would trip a voice. intro / outro open and close the film version.
  sub: {
    intro: 'Hey, you. Want to see how IceCube catches neutrinos from space? Stay close.',
    c1a: "The South Pole, in the polar night. Hmph. It's so cold my whiskers are freezing.",
    c1b: "See that little lit-up building? That's the IceCube Lab. But the real telescope isn't in there. It's under our feet.",
    c1c: "Stay close, we're going down! The ice here is almost three kilometres thick. The deeper we go, the fewer the bubbles and the clearer the ice.",
    c1d: "1,450 metres. Here's where the detector starts.",
    c1e: "This ball is a Digital Optical Module, a DOM. It doesn't glow. It just waits in the dark for light.",
    c2a: 'Sixty DOMs hang on one string, about 17 metres apart.',
    c2b: 'The next string is about 125 metres away.',
    c2c: '86 strings and 5,160 DOMs, from 1,450 metres all the way down to 2,450. Go on, look up.',
    c2d: 'A cubic kilometre of natural ice turned into a detector, with only a sprinkle of eyes inside.',
    c2e: 'Huh? What was that flash?',
    c3a: "Don't blink. I'll slow it down for you.",
    c3b: "The dashed line is the neutrino's path. It doesn't glow; the dashes are just my marker.",
    c3c: 'It smacks into a nucleus in the ice: ν_μ + N → μ⁻ + X',
    c3d: 'The muon it makes is charged and outruns light in ice, flinging out Cherenkov light at about 41°.',
    c3e: 'The light bounces around in the ice. Most of it is absorbed on the way; only a little reaches a DOM.',
    c3f: 'When the light arrives, and how much, gets recorded. These colours are records, not DOMs glowing.',
    c3g: 'This one was a lucky hit. Almost every neutrino flies straight through and leaves nothing.',
    c4a: 'Okay, those tracks were drawn by me, to explain.',
    c4b: 'All scientists really get is these records: where each DOM is, when it saw light, and how much.',
    c4c: 'From just that, can you find where it came from?',
    c4d: 'Now colour shows the time residual: cyan arrived earlier than predicted, orange later.',
    c4e: 'Scattering can make light late, but never earlier than a straight path. Arriving too early means the direction is wrong.',
    c4f: 'Over to the algorithm: a rough first guess, then step-by-step corrections.',
    c4g: 'Then resampling estimates the error. Remember, every direction comes with an uncertainty.',
    c4h: 'A real analysis also fits the vertex and energy and models the ice and the detector. Ours is the simple version.',
    c5a: 'Flip that direction around and stretch it out into the sky.',
    c5b: 'At the South Pole the horizon is the celestial equator. This direction is about 6° below it, in the northern sky.',
    c5c: "So what's hiding in that little patch of sky?",
    c5d: 'About four billion light-years away, at the heart of a galaxy, a supermassive black hole is feeding, and a jet near light speed points right at Earth.',
    c5e: 'Protons in the jet hit photons and make pions. When a pion decays, out comes a neutrino.',
    c5f: 'Photons get absorbed and charged particles get bent by magnetic fields. Only neutrinos fly straight here.',
    c5g: 'It set off four billion years ago, dived into the Earth below the horizon, travelled some 1,300 km through it and reached the ice at the Pole.',
    c5h: 'On 22 September 2017, IceCube really caught one like this: IceCube-170922A.',
    c5i: 'Inside its direction region sat a blazar flaring in gamma rays: TXS 0506+056.',
    c5j: 'Direction, timing and observations at other wavelengths together made the case for a link, at about 3σ.',
    c5k: 'Nobody ever took a picture of that particle.',
    c5l: 'But the time and light it left told us where to look. Hmph. Not bad, right?',
    outro: "Done already? Next time I'll take you somewhere else. Not that I'm waiting for you or anything.",
  },
  tts: {
    c1d: 'Fourteen hundred and fifty metres. Here is where the detector starts.',
    c1e: 'This ball is a Digital Optical Module, a D O M. It does not glow. It just waits in the dark for light.',
    c2a: 'Sixty D O Ms hang on one string, about seventeen metres apart.',
    c2b: 'The next string is about a hundred and twenty-five metres away.',
    c2c: 'Eighty-six strings and five thousand one hundred and sixty D O Ms, from fourteen fifty metres all the way down to twenty-four fifty. Go on, look up.',
    c3c: 'It smacks into a nucleus in the ice.',
    c3d: 'The muon it makes is charged and outruns light in ice, flinging out Cherenkov light at about forty-one degrees.',
    c3e: 'The light bounces around in the ice. Most of it is absorbed on the way; only a little reaches a D O M.',
    c3f: 'When the light arrives, and how much, gets recorded. These colours are records, not D O Ms glowing.',
    c4b: 'All scientists really get is these records: where each D O M is, when it saw light, and how much.',
    c5b: 'At the South Pole the horizon is the celestial equator. This direction is about six degrees below it, in the northern sky.',
    c5g: 'It set off four billion years ago, dived into the Earth below the horizon, travelled some thirteen hundred kilometres through it, and reached the ice at the Pole.',
    c5h: 'On the twenty-second of September, twenty seventeen, IceCube really caught one like this: IceCube one seven zero nine two two A.',
    c5i: 'Inside its direction region sat a blazar flaring in gamma rays: T X S zero five zero six, plus zero five six.',
    c5j: 'Direction, timing and observations at other wavelengths together made the case for a link, at about three sigma.',
  },
  cat: {
    hello: 'Hey, you. Want to see how IceCube catches neutrinos from space? Stay close.',
    cold: "So cold… where we're going is right under our feet.",
    domSize: "33 cm. About my size when I'm curled up.",
    deepcore: 'The denser cluster in the middle is DeepCore, for lower-energy neutrinos.',
    tryReal: 'Try "True size" up top. The DOMs almost vanish. The ice is mostly empty… huh.',
    what: '…!',
    tall: 'Look up… it goes on and on.',
    clear: 'Fewer bubbles now… huh.',
    notFromHole: "The neutrino doesn't escape from the black hole. It's made out in the jet.",
    through: 'It came from the northern sky and burrowed under the ground to get here… I see.',
    slow: 'Nice and slow.',
    bang: 'Oh, a hit.',
    cone: 'The light spreads on a cone, like the wake of a boat.',
    inspect: 'Click a DOM to see what it recorded.',
    think: 'Only colours and times… let me think.',
    turn: 'Drag the two sliders to turn the candidate track until predicted and recorded times agree.',
    close: "That's close… neat.",
    plateau: "The last few degrees are beyond the eye. The algorithm's turn.",
    done: 'Found it. It comes with a ring of uncertainty, and that is the honest answer.',
    sky: "That direction is below the horizon, huh.",
    maybe: 'One event can only say "maybe". It takes many pieces of evidence to say "that one".',
    sleep: 'The ice is quiet again… nap time.',
    poke: ['Meow? What.', 'Hmph. Stop poking.', 'IceCube DOMs all look downward.', 'Five thousand DOMs. More than all the fish treats I ever had.', 'Want to try the Lab?', "Scattering makes light late. Like me getting up."],
  },
  labels: {
    lab: 'IceCube Lab',
    dom: 'DOM · 33 cm across',
    cat: 'Scale: one cat ≈ 30 cm',
    human: 'Person · 1.7 m',
    vBracket: '≈ 17 m',
    hBracket: '≈ 125 m',
    bar: '100 m',
    tower: 'Shanghai Tower, 632 m (for scale)',
    cube: '1 km³ reference frame (not a wall)',
    deepcore: 'DeepCore',
    dust: 'Dust layer (≈ 2,000–2,100 m)',
    bedrock: 'Bedrock (≈ 2,820 m)',
    surface: 'Ice surface 0 m',
    nu: 'Neutrino ν (marker)',
    mu: 'Muon μ',
    x: 'Hadronic shower X',
    atm: 'Atmospheric muon (background)',
    angle: 'θc ≈ 41°',
    pole: 'South Pole · IceCube',
    earthScale: 'Earth · about 12,700 km across',
    galaxyScale: 'Milky Way · about 100,000 light-years across',
    farScale: 'About 4 billion light-years away',
    equator: 'Horizon = celestial equator',
    north: 'Northern sky (below the horizon)',
    south: 'Southern sky',
    chord: '≈1,300 km under the ground',
    recoDir: 'Reconstructed direction (≈6° below the horizon)',
    schematic: 'Array schematic · original 86-string layout',
  },
  origin: {
    process: 'Sketch: one possible production process in the jet',
    p: 'proton p',
    g: 'photon γ',
    pi: 'pion π',
    nu: 'neutrino ν',
    lanes: ['photon γ', 'cosmic ray p⁺', 'neutrino ν'],
    laneNotes: ['absorbed by dust, gas or background light', 'bent by magnetic fields', 'arrives in a straight line'],
    source: 'source',
    earth: 'Earth',
    replay: 'Replay',
  },
  game: {
    title: 'Direction reconstruction',
    zenith: 'Zenith',
    azimuth: 'Azimuth',
    direct: 'Records explained by direct light',
    spread: 'Median time residual',
    scatterX: 'Predicted time (μs)',
    scatterY: 'Recorded time (μs)',
    run: 'Let the algorithm continue',
    running: 'Computing…',
    linefit: '① LineFit first guess',
    refine: '② Compare time residuals, adjust direction and position',
    boot: '③ Resample to estimate the uncertainty',
    result: 'Fit is {err}° from the simulated truth; statistical uncertainty ≈ {r90}° (90%, teaching model)',
    note: 'Simplified exercise: the track passes through the charge centre and its time offset is aligned automatically; real fits also free the vertex and energy and use an ice model.',
    reset: 'Start over',
    zero: 'Even the right direction never gives zero residuals: light scatters in ice.',
  },
  inspector: {
    title: 'DOM record',
    string: 'String',
    index: 'Number (top down)',
    depth: 'Depth',
    pos: 'Position (x, z)',
    first: 'First photon',
    charge: 'Light',
    pe: 'photoelectrons',
    pulse: 'Photon arrival times (teaching simulation)',
    none: 'This DOM recorded nothing in this event.',
    noise: 'A random noise record, unrelated to the event.',
    path: 'The physics layer highlights the sample light path that explains this record.',
    deep: 'DeepCore high-efficiency DOM',
  },
  sky: {
    title: 'The direction on the sky',
    teach: 'Teaching-event reconstruction (90%)',
    ic: 'IceCube-170922A region (90%)',
    txs: 'TXS 0506+056 (blazar, redshift 0.3365)',
    orion: 'Orion',
    ra: 'Right ascension',
    dec: 'Declination',
    note: "The teaching event is placed in IceCube-170922A's sky region for the story; the real event's per-DOM signals are not public and are not used here.",
    facts: 'IceCube-170922A deposited about 23.7 TeV; the most probable neutrino energy is about 290 TeV. Fermi-LAT found TXS 0506+056 flaring in gamma rays and MAGIC then detected it above 100 GeV. A chance coincidence is disfavoured at about 3σ; archival data from 2014–2015 also show a neutrino excess at about 3.5σ.',
  },
  lab: {
    title: 'Lab',
    intro: 'Three small experiments on the same teaching model. Each control changes the physics, not a screen filter.',
    scatter: 'Scattering',
    scatterNote: 'A shorter effective scattering length means more detours: light arrives later and more spread out.',
    lambda: 'Effective scattering length',
    background: 'Backgrounds',
    noise: 'Random noise (DOM dark noise)',
    atm: 'One atmospheric muon',
    clean: 'Space-time coincidence cleaning',
    cleanNote: 'Keep a record only if a neighbouring DOM on the same string fired within 1 μs.',
    atmNote: 'Tracks from above are mostly atmospheric muons; only tracks from below the horizon can be neutrinos that crossed the Earth.',
    kind: 'Event type',
    track: 'Track (ν_μ charged current)',
    cascade: 'Cascade (ν_e or neutral current)',
    kindNote: 'Cascade light spreads from almost a point: the energy is contained, but the direction is hard.',
    stats: 'Hit DOMs: {hits} · median first-light delay: {delay} ns',
    statsNoise: 'Noise records: {n} → {kept} after cleaning',
    recoStats: 'Reconstruction: {err}° from truth (statistical uncertainty {r90}°)',
    rerun: 'Re-run the event',
    reco: 'Reconstruct this event',
  },
  sources: {
    title: 'Sources and notes',
    about: 'About this page',
    aboutBody:
      'An independent interactive explainer, not affiliated with the IceCube Collaboration. The array geometry is generated from IceCube’s published parameters (original 86-string configuration; the IceCube Upgrade strings installed in 2025–26 are not drawn). The neutrino event is a teaching simulation: light production, propagation and scattering use simplified models (Pandel time distribution with AMANDA parameters); per-DOM times and charges are not real data. The reconstruction is a simplified exercise whose uncertainty comes from resampling; it is not IceCube’s angular resolution.',
    list: [
      ['IceCube detector', 'https://icecube.wisc.edu/science/icecube/'],
      ['IceCube quick facts', 'https://icecube.wisc.edu/about-us/facts/'],
      ['Detector paper: JINST 12, P03012 (2017)', 'https://arxiv.org/abs/1612.05093'],
      ['IceCube Masterclass: detecting neutrinos', 'https://masterclass.icecube.wisc.edu/en/icecube-and-neutrinos/detecting-neutrinos/'],
      ['Ice optics: SPICE-Mie, NIM A 711, 73 (2013)', 'https://arxiv.org/abs/1301.5361'],
      ['IceCube-170922A and TXS 0506+056: Science 361, eaat1378', 'https://arxiv.org/abs/1807.08816'],
      ['2014–15 neutrino excess from TXS 0506+056: Science 361, 147', 'https://arxiv.org/abs/1807.08794'],
      ['GCN 21916 (IceCube-170922A alert)', 'https://gcn.nasa.gov/circulars/21916'],
      ['IceCube press release (2018)', 'https://icecube.wisc.edu/news/press-releases/2018/07/icecube-neutrinos-point-to-long-sought-cosmic-ray-accelerator/'],
      ['IceCube Upgrade deployed (2026)', 'https://icecube.wisc.edu/news/press-releases/2026/02/the-icecube-neutrino-observatory-gets-a-major-upgrade-beneath-the-ice/'],
      ['Nobel Prize in Physics 2026 press release', 'https://www.nobelprize.org/prizes/physics/2026/press-release/'],
    ],
    credit: 'Made by CosmicTraveler – Yeoman · the mascot Yeoman is a real cat.',
  },
  end: {
    title: 'The ice is quiet again',
    lines: [
      'IceCube does not see neutrinos directly; it sees the light made after an interaction.',
      'The array is huge to catch enough of these very rare interactions.',
      'Sensors at different places record different times and amounts of light, and that lets us work the event back.',
      'Direction and source both carry uncertainty; one line on a screen does not prove everything.',
    ],
    again: 'Watch again',
    lab: 'Open the Lab',
    free: 'Explore freely',
  },
  fallback: 'Your browser has WebGL turned off, so the 3D film cannot run. Here is the script as text.',
};
