// Chinese copy (primary language). Yeoman narrates in its speech bubble (sub.*, voiced); cat.* are its extra
// lines for interactions. Persona: a tsundere cat with a sunny boy's voice: a sulky face, proud and a little
// grumpy ("哼"), warm underneath; it talks to the viewer and keeps every fact straight. Every number here also
// appears in the piece's facts ledger: astronomy/pieces/20261006a_icecube-nobel2026/master.md.

export default {
  meta: {
    title: '冰立方 IceCube',
    tagline: '一立方公里的黑暗，接收宇宙的一次微光',
    question: '一个看不见的粒子，怎样告诉我们应该望向宇宙的哪里？',
    start: '开始导览',
    explore: '自由探索',
    duration: '交互动画 · 约 {min} 分钟 · 随时可以暂停、拖动和接管', // {min}: the tour's length, filled in by the HUD
    nobel: '2026 年诺贝尔物理学奖授予 Francis Halzen，表彰冰立方中微子天文台和对天体物理高能中微子的发现。',
    nobelLink: '诺贝尔奖官方新闻稿',
    by: '星野旅人 Yeoman',
    teaching: '教学模拟：阵列按官方间距示意，逐 DOM 信号为模拟。',
  },
  ui: {
    play: '播放',
    pause: '暂停',
    resume: '返回导览',
    lang: 'EN',
    voiceOn: '配音：开',
    voiceOff: '配音：关',
    voiceNone: '配音：无',
    volume: '音量',
    volVoice: '人声',
    volMusic: '音乐',
    qualityLabel: '画质',
    qAuto: '自动',
    qHigh: '高',
    qMedium: '中',
    qLow: '省电',
    soundOn: '数据声音化：开',
    soundOff: '数据声音化：关',
    sources: '资料来源',
    lab: '实验台',
    settings: '显示设置',
    realSize: '真实尺寸',
    enlarged: '标记放大',
    sizeNote: '标记放大：位置不变，只放大显示',
    realNote: '真实尺寸：DOM 直径 33 cm，远看几乎消失；竖线是引导线',
    reduceMotion: '减少动态',
    quality: '画质',
    qualityHigh: '高',
    qualityLow: '省电',
    layers: '观察层',
    layerPhysics: '物理示意',
    layerRecord: '探测器记录',
    layerReco: '重建结果',
    physTime: '物理时间',
    slowmo: '慢放',
    stepBack: '后退 100 纳秒',
    stepFwd: '前进 100 纳秒',
    legendTime: '记录时刻',
    early: '早',
    late: '晚',
    legendSize: '标记大小 = 光量',
    legendRecord: '彩色标记表示“记录到信号”，不是 DOM 在发光',
    legendResid: '时间残差：记录 − 预测',
    residEarly: '记录比预测早',
    residOk: '吻合',
    residLate: '记录比预测晚',
    close: '关闭',
    replay: '再看一次',
    chapter: '章节',
    depth: '深度',
    meters: '米',
    keyboard: '空格 播放/暂停 · ←/→ 微调 · 1–6 章节 · L 观察层 · R 尺寸',
  },
  chapters: ['冰面', '尺度', '慢放', '重建', '来处', '回到天空'],
  // Narration: Yeoman says these lines in its speech bubble (no subtitles); `tts` holds the spoken form where
  // symbols or numbers would trip a voice. intro / outro open and close the film version.
  sub: {
    intro: '喂，说你呢。想看冰立方怎么抓住宇宙来的中微子吗？跟紧我。',
    c1a: '南极点，极夜。哼，冷得我胡子都快结冰了。',
    c1b: '看见那栋亮灯的小楼了吗？那是冰立方实验室。不过真正的望远镜不在楼里，在我们脚底下。',
    c1c: '跟紧我，往下钻！这里的冰将近三千米厚，越往下气泡越少，冰也越透明。',
    c1d: '1,450 米，到了，探测器就从这里开始。',
    c1e: '这个圆球叫数字光学模块，简称 DOM。它自己不发光，就在黑暗里等着光来。',
    c2a: '60 个 DOM 串成一根，上下每隔约 17 米挂一个。',
    c2b: '旁边那一根，隔着大约 125 米。',
    c2c: '一共 86 根、5,160 个 DOM，从地下 1,450 米一直排到 2,450 米。你抬头看看。',
    c2d: '一立方公里的天然冰，就这样成了探测器，里面的眼睛却装得稀稀拉拉。',
    c2e: '咦？刚才那一闪是什么？',
    c3a: '别眨眼，我把它放慢给你看。',
    c3b: '这条虚线是中微子的路线。它自己不发光，虚线是我画上去的记号。',
    c3c: '它一头撞上了冰里的原子核：ν_μ + N → μ⁻ + X',
    c3d: '撞出来的缪子带电，跑得比光在冰里还快，一路以约 41° 的角度甩出切伦科夫光。',
    c3e: '光在冰里东撞西撞，大多半路就被吸收了，只有一小部分碰到了 DOM。',
    c3f: '光到达的时刻和亮度都记下来了。这些彩色标记是记录，可不是 DOM 在发光。',
    c3g: '这一颗是撞上了的幸运儿。绝大多数中微子会直接穿过去，什么也不留下。',
    c4a: '好了，刚才那些轨迹是我为了讲清楚才画的。',
    c4b: '科学家真正拿到手的，只有这些记录：每个 DOM 在哪、什么时候收到光、收到多少。',
    c4c: '就凭这些，你能找回它是从哪儿来的吗？',
    c4d: '现在颜色换成了时间残差：青色是比预测早到，橙色是晚到。',
    c4e: '光会因为散射晚到，可绝不会比走直线还早。早到太多，就说明方向猜错了。',
    c4f: '剩下的交给算法：先粗估一个方向，再一点一点修正。',
    c4g: '最后用重抽样估一估误差。记住，任何方向都带着不确定度。',
    c4h: '真正的分析还要考虑顶点、能量、冰的光学性质和探测器响应。我们这个是简化版。',
    c5a: '把这个方向倒过来，一直延伸到天上。',
    c5b: '在南极点，地平线就是天赤道。这个方向在地平线下约 6°，指向北天。',
    c5c: '天上这一小块地方，到底藏着什么？',
    c5d: '约 40 亿光年外的一个星系中心，超大质量黑洞正在吞噬物质，旁边喷出接近光速的喷流，正好对着地球。',
    c5e: '喷流里的高能质子撞上光子，生出 π 介子，π 介子一衰变，就放出了中微子。',
    c5f: '光子会被吸收，带电粒子会被磁场带偏，只有中微子能一路直直地飞过来。',
    c5g: '它四十亿年前就出发了，最后从地平线下钻进地球，在地底穿行约 1,300 公里，来到南极的冰里。',
    c5h: '2017 年 9 月 22 日，冰立方真的抓到了这样一个事件：IceCube-170922A。',
    c5i: '它的方向区域里，正好有一个在伽马射线里耀发的耀变体：TXS 0506+056。',
    c5j: '方向、时间和多波段观测凑到一起，才算得上关联的证据，显著性约 3σ。',
    c5k: '我们从来没给那颗粒子拍过照片。',
    c5l: '可它留下的时间和光，告诉了我们该往哪里看。哼，厉害吧。',
    outro: '看完啦？下次再带你去别的地方。我才不是在等你回来呢。',
  },
  tts: {
    c1d: '一千四百五十米，到了，探测器就从这里开始。',
    c1e: '这个圆球叫数字光学模块，简称 D O M。它自己不发光，就在黑暗里等着光来。',
    c2a: '六十个 D O M 串成一根，上下每隔约十七米挂一个。',
    c2b: '旁边那一根，隔着大约一百二十五米。',
    c2c: '一共八十六根，五千一百六十个 D O M，从地下一千四百五十米，一直排到两千四百五十米。你抬头看看。',
    c3c: '它一头撞上了冰里的原子核。',
    c3d: '撞出来的缪子带电，跑得比光在冰里还快，一路以约四十一度的角度，甩出切伦科夫光。',
    c3e: '光在冰里东撞西撞，大多半路就被吸收了，只有一小部分碰到了 D O M。',
    c3f: '光到达的时刻和亮度都记下来了。这些彩色标记是记录，可不是 D O M 在发光。',
    c4b: '科学家真正拿到手的，只有这些记录：每个 D O M 在哪，什么时候收到光，收到多少。',
    c5b: '在南极点，地平线就是天赤道。这个方向在地平线下约六度，指向北天。',
    c5d: '约四十亿光年外的一个星系中心，超大质量黑洞正在吞噬物质，旁边喷出接近光速的喷流，正好对着地球。',
    c5e: '喷流里的高能质子撞上光子，生出派介子，派介子一衰变，就放出了中微子。',
    c5g: '它四十亿年前就出发了，最后从地平线下钻进地球，在地底穿行约一千三百公里，来到南极的冰里。',
    c5h: '二零一七年九月二十二日，冰立方真的抓到了这样一个事件，IceCube 一七零九二二 A。',
    c5i: '它的方向区域里，正好有一个在伽马射线里耀发的耀变体，T X S 零五零六，加，零五六。',
    c5j: '方向、时间和多波段观测凑到一起，才算得上关联的证据，显著性约三个西格玛。',
  },
  cat: {
    hello: '喂，说你呢。想看冰立方怎么抓住宇宙来的中微子吗？跟紧我。',
    cold: '好冷……我们要去的地方，在脚下呢。',
    domSize: '33 厘米，大概是我蜷起来那么大。',
    deepcore: '中间更密的那一簇叫 DeepCore，专门看能量更低的中微子。',
    tryReal: '点右上角的“真实尺寸”试试，DOM 几乎看不见了。冰里其实很空呢。',
    what: '……！',
    tall: '抬头看……好高呢。',
    clear: '气泡越来越少了呢。',
    notFromHole: '中微子不是从黑洞里逃出来的，是在外面的喷流里产生的。',
    through: '它从北边的天空来，钻过地下才到这儿，这样呢。',
    slow: '慢慢看。',
    bang: '啊，撞上了。',
    cone: '光沿着一个圆锥面散开，像船头划开的水波。',
    inspect: '点一个 DOM，看看它记下了什么。',
    think: '只看颜色和时间……嗯，我想想。',
    turn: '拖动下面两个滑块，转动候选轨迹，让预测时间和记录时间对上。',
    close: '很接近了，这样呢。',
    plateau: '最后几度，用眼睛已经分不清了。轮到算法。',
    done: '找到啦。不过它带着一圈误差，这是诚实的答案。',
    sky: '这个方向，在地平线下面呢。',
    maybe: '一个事件只能说可能。很多证据放在一起，才敢说就是它。',
    sleep: '冰下又安静了……我也该睡了。',
    poke: ['喵？干嘛。', '哼，别戳了。', '冰立方的 DOM 都朝下看哦。', '5,160 个 DOM，比我吃过的小鱼干还多。', '要不要去实验台玩玩？', '散射让光晚到，就像我起床一样。'],
  },
  labels: {
    lab: '冰立方实验室',
    dom: 'DOM · 直径 33 cm',
    cat: '比例参考：一只猫约 30 cm',
    human: '人 · 1.7 m',
    vBracket: '约 17 m',
    hBracket: '约 125 m',
    bar: '100 m',
    tower: '上海中心大厦 632 m（比例参考）',
    cube: '1 km³ 参考框（不是容器壁）',
    deepcore: 'DeepCore',
    dust: '尘埃层（约 2,000–2,100 m）',
    bedrock: '基岩（约 2,820 m）',
    surface: '冰面 0 m',
    nu: '中微子 ν（示意标记）',
    mu: '缪子 μ',
    x: '强子簇射 X',
    atm: '大气缪子（背景）',
    angle: 'θc ≈ 41°',
    pole: '南极点 · 冰立方',
    earthScale: '地球 · 直径约 1.3 万公里',
    galaxyScale: '银河系 · 直径约 10 万光年',
    farScale: '约 40 亿光年外',
    equator: '地平线 = 天赤道',
    north: '北天（在地平线以下）',
    south: '南天',
    chord: '地下穿行约 1,300 km',
    recoDir: '重建方向（地平线下约 6°）',
    schematic: '阵列示意 · 原始 86 根 string 配置',
  },
  origin: {
    process: '示意：喷流中一种可能的产生过程',
    p: '高能质子 p',
    g: '光子 γ',
    pi: 'π 介子',
    nu: '中微子 ν',
    lanes: ['光子 γ', '宇宙线 p⁺', '中微子 ν'],
    laneNotes: ['被尘埃、气体或背景光吸收', '被磁场偏转，方向乱了', '几乎不受阻挡，直线到达'],
    source: '源',
    earth: '地球',
    replay: '重放',
  },
  game: {
    title: '方向重建',
    zenith: '天顶角',
    azimuth: '方位角',
    direct: '能被直射光解释的记录',
    spread: '时间残差中位数',
    scatterX: '预测时间（μs）',
    scatterY: '记录时间（μs）',
    run: '让算法继续',
    running: '算法计算中…',
    linefit: '① 线性拟合给出初猜',
    refine: '② 比较时间残差，逐步调整方向和位置',
    boot: '③ 重抽样估计不确定度',
    result: '拟合方向与模拟真值相差 {err}°；统计不确定度约 {r90}°（90%，教学模型）',
    note: '简化练习：轨迹穿过记录的电荷重心，时间零点自动对齐；真实分析还要拟合顶点、能量，并使用冰的光学模型。',
    reset: '重新开始',
    zero: '即使方向完全正确，残差也不会是 0：光在冰里会散射。',
  },
  inspector: {
    title: 'DOM 记录',
    string: 'String',
    index: '编号（自上而下）',
    depth: '深度',
    pos: '位置 (x, z)',
    first: '首个光子时刻',
    charge: '光量',
    pe: '光电子',
    pulse: '光子到达时间分布（教学模拟）',
    none: '这个 DOM 在本次事件中没有记录到信号。',
    noise: '这是一次随机噪声记录，与事件无关。',
    path: '物理示意层中高亮了能解释这条记录的示意光路。',
    deep: 'DeepCore 高量子效率 DOM',
  },
  sky: {
    title: '天球上的方向',
    teach: '教学事件的重建区域（90%）',
    ic: 'IceCube-170922A 方向区域（90%）',
    txs: 'TXS 0506+056（耀变体，红移 0.3365）',
    orion: '猎户座',
    ra: '赤经',
    dec: '赤纬',
    note: '教学事件的天区设为与 IceCube-170922A 相同，便于讲解；真实事件的逐 DOM 信号未公开，这里没有使用。',
    facts: 'IceCube-170922A：沉积能量约 23.7 TeV，最可能的中微子能量约 290 TeV。Fermi-LAT 发现 TXS 0506+056 正处于伽马射线耀发，MAGIC 随后探测到 100 GeV 以上的伽马射线。偶然重合在约 3σ 水平被排除；回溯 2014–2015 年的数据，还发现一次约 3.5σ 的中微子超出。',
  },
  lab: {
    title: '实验台',
    intro: '三个小实验都作用在同一套教学模型上，参数改的是物理，不是画面滤镜。',
    scatter: '散射',
    scatterNote: '有效散射长度越短，光走的弯路越多，到达越晚、越分散。',
    lambda: '有效散射长度',
    background: '背景',
    noise: '随机噪声（DOM 暗噪声）',
    atm: '一条大气缪子',
    clean: '时空关联清洗',
    cleanNote: '同一根 string 上相邻 DOM 在 1 微秒内都有记录，才保留。',
    atmNote: '从上方来的轨迹多半是大气缪子；从地平线以下来的，才可能是穿过地球的中微子。',
    kind: '事件类型',
    track: '轨迹（ν_μ 带电流）',
    cascade: '级联（ν_e 或中性流）',
    kindNote: '级联的光几乎从一点散开：能量包得住，方向却难定。',
    stats: '击中 DOM：{hits} · 首光延迟中位数：{delay} ns',
    statsNoise: '噪声记录：{n} → 清洗后 {kept}',
    recoStats: '重建：与真值相差 {err}°（统计不确定度 {r90}°）',
    rerun: '重新运行事件',
    reco: '重建这一事件',
  },
  sources: {
    title: '资料来源与说明',
    about: '关于这个页面',
    aboutBody:
      '这是一个个人制作的交互式科普动画，与冰立方合作组没有隶属关系。阵列几何按冰立方官方参数生成（原始 86 根 string 配置，2025–26 年新增的 IceCube Upgrade 未绘制）。中微子事件为教学模拟：光的产生、传播和散射使用简化模型（Pandel 时间分布，参数来自 AMANDA），逐 DOM 的时间和光量不是真实数据。方向重建是简化练习，误差来自重抽样，不代表冰立方的真实角分辨率。',
    list: [
      ['冰立方探测器与参数', 'https://icecube.wisc.edu/science/icecube/'],
      ['冰立方 Quick Facts', 'https://icecube.wisc.edu/about-us/facts/'],
      ['探测器论文：JINST 12, P03012 (2017)', 'https://arxiv.org/abs/1612.05093'],
      ['IceCube Masterclass：探测中微子', 'https://masterclass.icecube.wisc.edu/en/icecube-and-neutrinos/detecting-neutrinos/'],
      ['冰的光学性质：SPICE-Mie, NIM A 711, 73 (2013)', 'https://arxiv.org/abs/1301.5361'],
      ['IceCube-170922A 与 TXS 0506+056：Science 361, eaat1378', 'https://arxiv.org/abs/1807.08816'],
      ['TXS 0506+056 的 2014–15 中微子超出：Science 361, 147', 'https://arxiv.org/abs/1807.08794'],
      ['GCN 21916（IceCube-170922A 警报）', 'https://gcn.nasa.gov/circulars/21916'],
      ['冰立方新闻稿（2018）', 'https://icecube.wisc.edu/news/press-releases/2018/07/icecube-neutrinos-point-to-long-sought-cosmic-ray-accelerator/'],
      ['IceCube Upgrade 部署完成（2026）', 'https://icecube.wisc.edu/news/press-releases/2026/02/the-icecube-neutrino-observatory-gets-a-major-upgrade-beneath-the-ice/'],
      ['2026 年诺贝尔物理学奖新闻稿', 'https://www.nobelprize.org/prizes/physics/2026/press-release/'],
    ],
    credit: '制作：星野旅人 Yeoman · 吉祥物 Yeoman 是一只真实的猫。',
  },
  end: {
    title: '冰下重新安静下来',
    lines: ['它不是直接看见中微子，而是看相互作用后产生的光。', '阵列这么大，是为了从极少发生的相互作用里获得足够机会。', '不同位置的传感器记下了不同的时间和光量，这些能帮助反推事件。', '最终的方向和来源都有不确定度，屏幕上的一根线证明不了一切。'],
    again: '再看一次',
    lab: '打开实验台',
    free: '自由探索',
  },
  fallback: '你的浏览器没有开启 WebGL，无法显示三维动画。下面是这部短片的文字版。',
};
