// Background score player. The stems in audio/bgm/ (generated by web/_tools/bgm.mjs): `intro` under the film's title
// card, `tour` in step with the tour clock, `outro` under the end card. One media element plays them in turn (iOS
// lets an element play outside a tap only after a tap has unlocked it, see mixer.js), through the mixer's music bus
// (the viewer's level, a dip while Yeoman speaks); silent at level 0, before the first tap, or without stems.
// Like the narration, stems are fetched into blob URLs so they can be seeked on a server without range support.
// A phone that renders slowly lets the page's clock fall behind real time. A stem that runs ahead is then not pulled
// back (every seek is a gap in the sound) but reported as `lead`, and the clock catches up with it, as with the voice.

const BEHIND = 0.5; // s the stem may lag the clock before it is moved forward
const AHEAD = 2.5; // s it may run ahead (the clock catches up) before it is moved back

export function createMusic({ base = 'audio/bgm', mixer }) {
  let manifest = null;
  let loaded = null; // name of the stem in the element
  let drift = 0; // stem time minus the clock's, s
  let exact = false; // the next sync moves the stem to the clock (a new stem, or the clock jumped)
  const stems = new Map(); // name -> { url, file, dur }: url is the blob URL (or the file itself) once fetched
  const el = new Audio();
  el.preload = 'auto';
  mixer.connect(el, 'music');
  // a page whose security policy refuses blob: media falls back to the file itself
  el.addEventListener('error', () => {
    const s = loaded && stems.get(loaded);
    if (!s || s.url === s.file || el.getAttribute('src') !== s.url) return;
    URL.revokeObjectURL(s.url);
    s.url = s.file;
    loaded = null; // reloaded and re-placed by the next sync
  });

  async function load() {
    try {
      const res = await fetch(`${base}/manifest.json`, { cache: 'no-cache' });
      if (!res.ok) return false;
      manifest = await res.json();
    } catch {
      return false;
    }
    Object.entries(manifest.stems || {}).forEach(([name, s]) => {
      const stem = { url: null, file: `${base}/${s.file}`, dur: s.dur };
      stems.set(name, stem);
      fetch(stem.file)
        .then((r) => (r.ok ? r.blob() : Promise.reject(new Error(`HTTP ${r.status}`))))
        .then((blob) => {
          stem.url = URL.createObjectURL(blob);
        })
        .catch(() => {
          stem.url = stem.file; // stream instead (plays, but may not seek on such a server)
        });
    });
    return true;
  }

  function seek(t) {
    try {
      el.currentTime = t;
    } catch {
      /* not seekable yet: `exact` repeats the seek once it is */
    }
  }

  return {
    load,
    get available() {
      return Boolean(manifest);
    },
    /** For inspection: {name, time, paused} of the stem in the element, or null. */
    get current() {
      return loaded ? { name: loaded, time: el.currentTime, paused: el.paused } : null;
    },
    /**
     * Call every frame. want = {name, time, playing} (the stem and its position in seconds) or null for silence;
     * speaking = a narration line is on.
     */
    sync(want, speaking) {
      const s = manifest && want && mixer.level('music') > 0 ? stems.get(want.name) : null;
      if (!s || !want.playing || want.time < 0 || want.time > s.dur) {
        el.pause();
        drift = 0;
        return;
      }
      if (!s.url) return; // still loading
      if (loaded !== want.name) {
        loaded = want.name;
        el.src = s.url;
        exact = true;
      }
      mixer.resume();
      mixer.duck(speaking);
      drift = el.readyState >= 1 ? el.currentTime - want.time : 0;
      if (exact || (el.paused && Math.abs(drift) > 0.1) || drift < -BEHIND || drift > AHEAD) {
        seek(want.time);
        drift = 0;
        exact = el.readyState < 1; // a seek before the stem's metadata may not hold: repeat it until it can
      }
      if (el.paused) {
        el.play().catch(() => {
          /* not allowed until the viewer's first tap: retried on a later frame */
        });
      }
    },
    /** Seconds the playing stem is ahead of the clock (0 when none plays): the page adds it to its next frame. */
    get lead() {
      return !el.paused && el.readyState >= 2 && drift > 0 ? drift : 0;
    },
    /** The clock jumped (a seek): the next sync moves the stem to it instead of letting the clock catch up. */
    resync() {
      exact = true;
    },
    /** Pause at once, e.g. when the page is hidden (no frames run then); the next sync resumes. */
    pause() {
      el.pause();
    },
  };
}
