// Background score player. The stems in audio/bgm/ (generated by web/_tools/bgm.mjs): `intro` under the film's title
// card, `tour` in step with the tour clock, `outro` under the end card. Played through the mixer's music bus (the
// viewer's level, a dip while Yeoman speaks); silent at level 0, before the first click, or when there are no stems.
// Like the narration, stems are fetched into blob URLs so they can be seeked on a server without range support.

const RESEEK = 0.5; // s of drift before a stem is moved to the clock

export function createMusic({ base = 'audio/bgm', mixer }) {
  let manifest = null;
  let current = null; // name of the stem in use
  const stems = new Map(); // name -> {el, ready, dur}

  async function load() {
    try {
      const res = await fetch(`${base}/manifest.json`, { cache: 'no-cache' });
      if (!res.ok) return false;
      manifest = await res.json();
    } catch {
      return false;
    }
    Object.entries(manifest.stems || {}).forEach(([name, s]) => {
      const entry = { el: new Audio(), ready: false, dur: s.dur };
      entry.el.preload = 'auto';
      mixer.connect(entry.el, 'music');
      stems.set(name, entry);
      const url = `${base}/${s.file}`;
      fetch(url)
        .then((r) => (r.ok ? r.blob() : Promise.reject(new Error(`HTTP ${r.status}`))))
        .then((blob) => {
          entry.el.src = URL.createObjectURL(blob);
          entry.ready = true;
        })
        .catch(() => {
          entry.el.src = url; // stream instead (plays, but may not seek on such a server)
          entry.ready = true;
        });
    });
    return true;
  }

  function pauseAll() {
    stems.forEach((s) => s.el.pause());
  }

  return {
    load,
    get available() {
      return Boolean(manifest);
    },
    /** For inspection: {name, time, paused} of the stem in use, or null. */
    get current() {
      const s = current && stems.get(current);
      return s ? { name: current, time: s.el.currentTime, paused: s.el.paused } : null;
    },
    /**
     * Call every frame. want = {name, time, playing} (the stem and its position in seconds) or null for silence;
     * speaking = a narration line is on.
     */
    sync(want, speaking) {
      if (!manifest || !want || mixer.level('music') === 0) {
        pauseAll();
        return;
      }
      const s = stems.get(want.name);
      if (!s || !s.ready) return;
      if (current && current !== want.name) stems.get(current).el.pause();
      current = want.name;
      if (!want.playing || want.time < 0 || want.time > s.dur) {
        s.el.pause();
        return;
      }
      mixer.resume();
      mixer.duck(speaking);
      if (s.el.paused) {
        s.el.currentTime = want.time;
        s.el.play().catch(() => {
          /* not allowed yet: retried on a later frame */
        });
      } else if (Math.abs(s.el.currentTime - want.time) > RESEEK) {
        s.el.currentTime = want.time;
      }
    },
  };
}
